include: package:very_good_analysis/analysis_options.yaml

formatter:
  page_width: 100

linter:
  rules:
    always_use_package_imports: false
    avoid_positional_boolean_parameters: false
    cascade_invocations: false
    document_ignores: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    require_trailing_commas: false
    sort_constructors_first: false
