name: journal
description: "A simple log recorder usable both from libraries and applications."
repository: https://github.com/skreborn/journal
version: 0.4.0

topics:
  - dart
  - utility
  - logging
  - cli

workspace:
  - example
  - packages/android
  - packages/android/example
  - packages/logging
  - packages/logging/example
  - packages/stdio
  - packages/stdio/example
  - packages/web
  - packages/web/example

environment:
  sdk: ^3.7.0

dependencies:
  meta: ^1.9.1
  stack_trace: ^1.10.0

dev_dependencies:
  very_good_analysis: ^7.0.0
