name: journal_android
description: "An output targeting Android devices for `journal`."
repository: https://github.com/skreborn/journal
version: 0.1.0

topics:
  - journal
  - android

resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  ffi: ^2.1.0
  journal: ^0.4.0
  stack_trace: ^1.10.0
